name: RankMeUp
main: net.beastnode.closeminded.plugins.rankmeup.RankMeUp
version: 0.1
author: tuxed
permissions:
    rankmeup.*:
        description: Alias for rankup and reload permissions
        children:
            rankmeup.rankup: true
    rankmeup.rankup:
        description: Let users rank up
    rankmeup.reload:
        description: Reload the plugin
        default: op
commands:
    rankup:
        description: Rank yourself up
